name: CI

on:
  push:         # Este evento se activará en cualquier push
    branches:   # Para todas las ramas
      - '**'    # Este patrón incluye todas las ramas
  pull_request: # Este evento se activará en cualquier pull request
    branches:   # Para todas las ramas
      - '**'    # Este patrón incluye todas las ramas

jobs:
  test: # Ejecución de los tests del backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
        working-directory: backend

  build: # Ejecución de la build del backend
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
        working-directory: backend